apiVersion: v1
kind: Pod
metadata:
  name: belongtech
  namespace: default
spec:
  containers:
  - name: belong
    image: dhageakshay/belongtech:web
    command: [python manage.py runserver && sleep 3600']
  - name: belongtech
    image: dhageakshay/belongtech:db
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
